### ISSUE TITLE
NPE in RepositoryNameCompleter when try to complete empty folder

### ISSUE THREAD

**Issue by Krasnyanskiy** [Jaspersoft/jrsh#176]
Suppose, I have such repository structure:
```bash
"/temp"
"/templates"
```
And both folders are empty. In this case when I try to complete
```java
$ export repository /temp[Tab]
```
I get `NullPointerException`.
```bash
jrsh jasperadmin%jasperadmin@localhost:8085
You have logged in as jasperadmin
$> export repository /temp
temp/        templates/   
$> export repository /temp[Tab]
Exception in thread "main" java.lang.NullPointerException
        at com.jaspersoft.jasperserver.jrsh.completion.completer.RepositoryNameCompleter.download(RepositoryNameCompleter.java:195)
        at com.jaspersoft.jasperserver.jrsh.completion.completer.RepositoryNameCompleter.complete(RepositoryNameCompleter.java:72)
        at jline.console.completer.ArgumentCompleter.complete(ArgumentCompleter.java:152)
        at jline.console.completer.AggregateCompleter$Completion.complete(AggregateCompleter.java:121)
        at jline.console.completer.AggregateCompleter.complete(AggregateCompleter.java:80)
        at jline.console.ConsoleReader.complete(ConsoleReader.java:3261)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2621)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
        at com.jaspersoft.jasperserver.jrsh.evaluation.strategy.impl.ShellEvaluationStrategy.eval(ShellEvaluationStrategy.java:71)
        at com.jaspersoft.jasperserver.jrsh.runner.App.main(App.java:52)
```

**Comment by Krasnyanskiy** [comment]
We've slightly changed behaviour of `RepositoryNameCompleter` in [this](https://github.com/Jaspersoft/jrsh/commit/b56314e65b7d5cfd4c479aec22aa9a425a1aeea6) commit. And so far we got rid of `NPE` in completer. But along with that we got unexpected resource completion behaviour:

```bash
$ export repository /templates/[Tab]templates/
```
The `RepositoryNameCompleter` adds folder twice.
